### PR TITLE
upgrade to Jest 2.0.0, Dropwizard 1.0.0, Elasticsearch 2.4.1

### PR DESCRIPTION
**Pull request by ElMoselYEE**
Jest 0.7.1 has issues decoding errors (error thrown while decoding errors), so for our project we needed the more recent version that fixes this problem. 

Seems too simple to be true, but all the tests pass. I'm unsure about the correct versioning to use.

It's my first PR ever, go easy on me!

### CODE REVIEW

**Comment by ctrimble** [comment]
@ElMoselYEE  Thanks for the PR.  I will have some time to look at this next week.

**Comment by ctrimble** [comment]
Sorry that I let this sit for so long.  Taking a look now.

**Comment by ctrimble** [comment]
@ElMoselYEE this doesn't look bad at all.  As far as versioning, you should not have moved the project off of a SNAPSHOT version.  That is something that is done at release time.  It was a good idea to move us up at least a minor, since you are changing compatibility with Elasticsearch versions.

On that topic, I am going to need to let this sit just a little longer as I figure out how this project should handle Jest's versioning strategy.  They are dropping support for older ES versions as they develop, so this project may need several active versions running in parallel.

**Comment by ElMoselYEE** [comment]
Thanks for the tips. I'm curious what you come up with for handling versioning.

**Comment by ElMoselYEE** [comment]
it's been 5y, house cleaning my open PRs

**Pull request closed without merging**
